name: CD - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'OEF'

            # Verifikasi apakah direktori ada
            ls ~/f-bee24001186-km7-juh-mediahandler-ch6/src

            # Jika tidak ada, clone repositori
            git clone https://github.com/Juhar-riski/f-bee24001186-km7-juh-mediahandler-ch6.git || true
            cd ~/f-bee24001186-km7-juh-mediahandler-ch6/src

            git pull origin main

            npm install

            npx prisma generate

            pm2 restart "cepakjeder" || pm2 start src/index.js --name "cepakjeder"

            pm2 save

            # Menambahkan pm2 ke startup agar otomatis berjalan saat server reboot
            pm2 startup systemd --hp /home/ubuntu
            pm2 save
          OEF
