name: CD - Deploy to EC2

on:
  push:
    branches:
      - main  # atau branch lain yang digunakan untuk deployment
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'OEF'

            cd ~/project/f-bee24001186-km7-juh-mediahandler-ch6/src

            git pull origin main

            npm install

            npx prisma generate

            pm2 restart "cepakjeder" || pm2 start src/index.js --name "cepakjeder"

            pm2 save

            # Menambahkan pm2 ke startup agar otomatis berjalan saat serverr reboot
            pm2 startup systemd --hp /home/ubuntu
            pm2 save
          OEF
