name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy files to EC2 server
        run: |
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Masuk ke direktori aplikasi
            cd /home/${{ secrets.EC2_USER }}/app

            # Instal dependensi jika belum ada
            npm install

            # Set up Prisma migrations jika diperlukan
            npx prisma migrate deploy

            # Pastikan PM2 berjalan, jika tidak jalankan dengan PM2
            pm2 restart app || pm2 start dist/app.js --name "app"

            # Restart server PM2 (jika ada perubahan konfigurasi atau file)
            pm2 reload all
          EOF

      - name: Clean up SSH key
        run: |
          rm -f ec2_key.pem
