name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'OEF'

            # Navigate to project directory (adjust as needed)
            cd ~/f-bee24001186-km7-juh-mediahandler-ch6

            # Pull latest changes from the repo
            git pull origin main

            # Install dependencies
            npm install

            # Prisma setup (adjust if you use migrations)
            npx prisma generate

            # Restart the app with PM2, or start if not running
            pm2 restart "cepakjeder" || pm2 start src/index.js --name "cepakjeder"

            # Save the PM2 process list
            pm2 save

            # Set PM2 to restart on system boot
            pm2 startup systemd --hp /home/ubuntu
            pm2 save

          OEF
